// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByjXue0d5UiEmoXErsXf6tbADnesXQ4G8',
    appId: '1:183398183101:web:479179d47f77c6d1b5c7d4',
    messagingSenderId: '183398183101',
    projectId: 'pizaaz-corner-project',
    authDomain: 'pizaaz-corner-project.firebaseapp.com',
    storageBucket: 'pizaaz-corner-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl_lXCYPDHo1aj2neDnjnxqyYWptWpauk',
    appId: '1:183398183101:android:4bacd8eaf36908b5b5c7d4',
    messagingSenderId: '183398183101',
    projectId: 'pizaaz-corner-project',
    storageBucket: 'pizaaz-corner-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTtAP1ceHvHVyIA6Ow4qtbZSxIk-KLYPM',
    appId: '1:183398183101:ios:0f54bf7d9713aeedb5c7d4',
    messagingSenderId: '183398183101',
    projectId: 'pizaaz-corner-project',
    storageBucket: 'pizaaz-corner-project.appspot.com',
    androidClientId: '183398183101-2llgmufuvr3eofek1ksmh1fjp2vf7023.apps.googleusercontent.com',
    iosClientId: '183398183101-kbkpb5cqedect5hcn4t4jm8bcshhsiua.apps.googleusercontent.com',
    iosBundleId: 'com.example.pizzaCornerAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTtAP1ceHvHVyIA6Ow4qtbZSxIk-KLYPM',
    appId: '1:183398183101:ios:0f54bf7d9713aeedb5c7d4',
    messagingSenderId: '183398183101',
    projectId: 'pizaaz-corner-project',
    storageBucket: 'pizaaz-corner-project.appspot.com',
    androidClientId: '183398183101-2llgmufuvr3eofek1ksmh1fjp2vf7023.apps.googleusercontent.com',
    iosClientId: '183398183101-kbkpb5cqedect5hcn4t4jm8bcshhsiua.apps.googleusercontent.com',
    iosBundleId: 'com.example.pizzaCornerAdminPanel',
  );
}
